<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Travel Requests Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; }
        .title { font-size: 18px; font-weight: bold; margin-bottom: 10px; }
        .subtitle { color: #666; margin-bottom: 20px; }
        .info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .status { padding: 4px 8px; border-radius: 4px; font-size: 10px; }
        .status-pending { background-color: #fef3c7; color: #d97706; }
        .status-approved { background-color: #d1fae5; color: #065f46; }
        .status-rejected { background-color: #fee2e2; color: #b91c1c; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">VoyageHub - Travel Requests Report</div>
        <div class="subtitle">Generated on {{ now()->format('F d, Y H:i') }}</div>
    </div>

    @if(!empty($filters) && array_filter($filters))
        <div class="filters">
            <h3>Applied Filters:</h3>
            @if(isset($filters['status']) && $filters['status'])
                <div class="filter-item">
                    <span class="filter-label">Status:</span> {{ ucfirst($filters['status']) }}
                </div>
            @endif
            @if(isset($filters['start_date']) && $filters['start_date'])
                <div class="filter-item">
                    <span class="filter-label">From:</span> {{ \Carbon\Carbon::parse($filters['start_date'])->format('M d, Y') }}
                </div>
            @endif
            @if(isset($filters['end_date']) && $filters['end_date'])
                <div class="filter-item">
                    <span class="filter-label">To:</span> {{ \Carbon\Carbon::parse($filters['end_date'])->format('M d, Y') }}
                </div>
            @endif
            @if(isset($filters['user_id']) && $filters['user_id'])
                <div class="filter-item">
                    <span class="filter-label">User:</span> {{ $travelRequests->first()?->user->name ?? 'N/A' }}
                </div>
            @endif
        </div>
    @endif

    <div class="info">
        <strong>Total Requests:</strong> {{ $travelRequests->count() }}<br>
        <strong>Approved:</strong> {{ $travelRequests->where('status', 'approved')->count() }}<br>
        <strong>Pending:</strong> {{ $travelRequests->where('status', 'pending')->count() }}<br>
        <strong>Rejected:</strong> {{ $travelRequests->where('status', 'rejected')->count() }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Requester</th>
                <th>Title</th>
                <th>Destination</th>
                <th>Purpose</th>
                <th>Status</th>
                <th>Requested Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($travelRequests as $request)
                <tr>
                    <td>{{ $request->user->name ?? 'N/A' }}</td>
                    <td>{{ $request->title }}</td>
                    <td>{{ $request->destination }}</td>
                    <td>{{ $request->purpose ?: 'Not specified' }}</td>
                    <td>
                        <span class="status status-{{ $request->status ?: 'pending' }}">
                            {{ ucfirst($request->status ?: 'pending') }}
                        </span>
                    </td>
                    <td>{{ $request->created_at->format('M d, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        This report was generated by VoyageHub Admin System
    </div>
</body>
</html>